### ISSUE TITLE
Step 08 Solution

### ISSUE THREAD

**Issue by 220284hk** [udacity/andfun-kotlin-guess-it#20]
@SudKul 
Hello, firstly, thank you for writing the solutions. Following each commit has helped me to write cleaner code and understand the pertinent concepts better e.g. encapsulation.

For solution 08 I was wondering the reasoning behind 1) the onPlayAgainComplete() method and 2) storing the score as a LiveData.

1) It seems, to me, that once we navigate away from the scoreFragment, the scoreViewModel will be cleared anyway so changing the value of _eventPlayAgain to false is not meaningful i.e. the next viewModel being referenced won't be the same viewModel as before. 

2) The score seems neither transient nor live, it is a value that is being passed from the previous fragment. Hence, why is it a good idea to store this value in the viewModel? 

If there is a particular reason for this then I would love to be enlightened. If it's good coding practice then I will take it in good faith. Thanks once again for your help so far.

**Comment by SudKul** [comment]
Hi @220284hk 
We are delighted that the commit history is helping you understand the code better. 

I encourage you to post your query on the Udacity Knowledge hub. Our network of mentors will be able to clarify in detail. Also, all current and future students will be able to view the expert comments/become part of the discussion. 

In case, you find any enhancement/improvement suggestions, you can raise a PR here. 

Happy to review your suggestions/PRs.
Thank you.
