### ISSUE TITLE
BUG: Crash on Rotation in Game 

### ISSUE THREAD

**Issue by Tarek-Bohdima** [udacity/andfun-kotlin-guess-it#27]
steps to recreate Bug:

1. start the game
2. play and rotate screen
3. finish to the end 
4. crash happens upon navigating to ScoreFragment

 
https://github.com/udacity/andfun-kotlin-guess-it/blob/c3f56e3910bb90ffa38d7b1f09eb3664f20e3829/app/build.gradle#L66
upgrading dependencies to androidx fix it:

// Navigation
//    implementation "android.arch.navigation:navigation-fragment-ktx:1.0.0-rc02"
//    implementation "android.arch.navigation:navigation-ui-ktx:1.0.0-rc02"
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.5"
    implementation "androidx.navigation:navigation-ui-ktx:2.3.5"

**Comment by SudKul** [comment]
For some unknown reasons, v2.3.5 were causing issues while building the app. 
However, I have upgraded the Navigation dependencies to 2.3.4 in this [commit](https://github.com/udacity/andfun-kotlin-guess-it/commit/9cc789afb07009a9d0c34164be85ff0875209071).
