### ISSUE TITLE
Code is outdated 

### ISSUE THREAD

**Issue by adriantache** [udacity/andfun-kotlin-guess-it#6]
ViewModelProviders is deprecated

**Comment by lswitaj-ynd** [comment]
Up, I also have a problem with that. Could you update the code, please?
Replacing ViewModelProviders with ViewModelProvider doesn't work properly.

Best,
Luc

**Comment by yegarti** [comment]
> Up, I also have a problem with that. Could you update the code, please?
> Replacing ViewModelProviders with ViewModelProvider doesn't work properly.
> 
> Best,
> Luc

Replace
`viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)`
with
`viewModel = ViewModelProvider(this).get(GameViewModel::class.java)`

**Comment by lswitaj-ynd** [comment]
The result is - crash. It's not rotation-proof

**Comment by lswitaj-ynd** [comment]
`viewModel = ViewModelProvider(this).get(GameViewModel::class.java)`
Result - crash. It's not rotation-proof

**Comment by yegarti** [comment]
Do you mean rotating the device and navigating to a different fragment? If you do this is 
a different issue discussed here #7

**Comment by lswitaj-ynd** [comment]
Thanks a lot, it helped

**Comment by danpgomez** [comment]
> Replace
> `viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)`
> with
> `viewModel = ViewModelProvider(this).get(GameViewModel::class.java)`

Unfortunately this did not work for me. I get the following error which seems to indicate that it is expecting a `ViewModelStore` or a `ViewModelStoreOwner` + a `ViewModelProvider.Factory`. 

```
None of the following functions can be called with the arguments supplied: 
public constructor ViewModelProvider(@NonNull p0: () -> ViewModelStore, @NonNull p1: ViewModelProvider.Factory) defined in androidx.lifecycle.ViewModelProvider
public constructor ViewModelProvider(@NonNull p0: ViewModelStore, @NonNull p1: ViewModelProvider.Factory) defined in androidx.lifecycle.ViewModelProvider
public constructor ViewModelProvider(@NonNull p0: ViewModelStoreOwner, @NonNull p1: ViewModelProvider.Factory) defined in androidx.lifecycle.ViewModelProvider
```

**Comment by masiorama** [comment]
It does work for me. @danpgomez are you sure your code is fully updated?

**Comment by danpgomez** [comment]
My mistake @masiorama . It actually does compile successfully after updating. Thank you! 😊

**Comment by YASH2803** [comment]
> ViewModelProviders is deprecated

At the start of the lesson they say that the instructor notes will be updated from time to time but they never do so!

**Comment by YASH2803** [comment]
At the start of the lesson they say that the instructor notes will be updated from time to time but they never do so!

**Comment by mdg121212** [comment]
I have had many issues with the outdated code here.  As far as this app, I had to go in and update all of the outdated dependencies (convert everything to androidx), and allow the deprecated method to stay (it just has a mark through it and a warning, it still works).  Also had to add this the the build.gradle(Module:app)  in the android { } block: 

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

For me (mid lesson 5 in this google training course) the app functions after doing those things.  I would have documented them more clearly, but it has been one frustration after another with this code ( I suppose a silver lining is having to figure out workable solutions).  Hope this helps someone!

**Comment by AtalKhandelwal** [comment]
App is automatically getting close without any logcat.

Also for resolving ViewProvider issue I have added the following dependency for resolving
   implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
   implementation "androidx.lifecycle:lifecycle-viewmodel:2.2.0"
which resolves View provider issue but not app closing issue.

**Comment by TheCodingArcher** [comment]
**Update your dependencies**:
In Project module:
`classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.1"`

In App module:
```
implementation "androidx.navigation:navigation-fragment-ktx:2.3.1"
implementation "androidx.navigation:navigation-ui-ktx:2.3.1"

apply plugin: "androidx.navigation.safeargs.kotlin"
```

**Comment by monojk** [comment]
In Excercise 22 "Add a ViewModelFactory":

In ScoreFragment.kt using ViewModelProvider doesn't compile., whereas in GameFragment.kt it does. 

![viewmodelprovider](https://user-images.githubusercontent.com/25121142/146670975-d2bf101e-3817-41d4-8047-640bd4adc961.jpg)

**Comment by SudKul** [comment]
We have recently [upgraded](https://github.com/udacity/andfun-kotlin-guess-it/commit/006b7482a0bf8e8cb4a3d503c3f15f3fc3b5a143) the `master` branch code with newer AndroidX dependencies.
Hopefully, the app will work fine now. 
However, we recommend using the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
