### ISSUE TITLE
Abrupt termination

### ISSUE THREAD

**Issue by vasanst** [udacity/andfun-kotlin-guess-it#9]
Hi,
After the optional lesson's (haptic feedback) code is installed, the application terminates abruptly after "Play" is clicked.  No logcat details reported.  Please help.
Thanks.
Vasan S T

**Comment by SudKul** [comment]
We have recently [upgraded](https://github.com/udacity/andfun-kotlin-guess-it/commit/006b7482a0bf8e8cb4a3d503c3f15f3fc3b5a143) the code with newer AndroidX dependencies.
Hopefully, the app will work fine now.
However, we recommend using the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
